name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK   
        uses: actions/setup-dotnet@v4.0.0
      - name: Publish .NET Core Project
        run: dotnet publish OpenAI-API-Dashboard/OpenAI-API-Dashboard.csproj --configuration Release --output release --nologo
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
 
