name: Deploy to GitHub Pages
# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
	jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
		    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7
            # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish OpenAI-API-Dashboard.csproj -c Release -o release --nologo

    - name: Commit wwwroot to GitHub Pages
      uses: clems67/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
